spring:
  application:
    name: EasyTask
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: Rohit@2210
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

